language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew build

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
