language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
      - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

script: "./gradlew clean check"

env:
  global:
    secure: ""

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
