---
project_identifier: open-link-with

files:
  - source: '/base-translations/src/main/res/values/strings.xml'
    translation: '/base-translations/src/main/res/values-%android_code%/strings.xml'
    languages_mapping:
      android_code:
        ar: ar
        de: de
        es-ES: es
        fi: fi
        fr: fr
        hi: hi
        hr: hr
        id: in
        it: it
        ja: ja
        ko: ko
        nl: nl
        pl: pl
        pt-BR: pt-rBR
        pt-PT: pt-rPT
        ru: ru
        sv-SE: sv
        tr: tr
        uk: uk
        vi: vi
        zh-CN: zh-rCN
        zh-TW: zh-rTW
